name: MineAPI
authors: [w67clement]
main: com.w67clement.mineapi.MineAPI
description: An API to make it easy some codes.
website: https://w67clement.github.io/plugins/MineAPI
version: 2.1.0
load: startup

commands:
  MineAPI:
    description: The MineAPI command.
    usage: /MineAPI <subCommand>
  AdvancedVersion:
    description: Gets the version of the server.
    usage: /AdvancedVersion

permissions:
  mineapi.*:
    description: All permissions of MineAPI.
    default: op
    children:
      mineapi.update_notifications: true
      mineapi.cmd.*: true
  mineapi.cmd.*:
    description: All permissions of MineAPI's commands.
    default: op
    children:
      mineapi.cmd.mineapi: true
      mineapi.cmd.advancedversion: true