name: MineAPI
authors: [67clement]
main: com.aol.w67clement.mineapi.MineAPI
description: An API to make it easy some codes.
website: https://67clement.github.io/plugins/MineAPI
version: 1.5.1

commands:
  AdvancedVersion:
    description: Gets the version of the server.
    usage: /AdvancedVersion

permissions:
  mineapi.*:
    description: All permissions of MineAPI.
    default: op
    children:
      mineapi.update_notifications: true
      mineapi.cmd.*: true
  mineapi.cmd.*:
    description: All permissions of MineAPI's commands.
    default: op
    children:
      mineapi.cmd.advancedversion: true